### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [zmzhang2000/trustworthy-alignment#3]
when i use Llama-3.1-8B-Instruct and transformers==4.45.1, i got error below:

> ******************[end] Initialized Reward Model [end] (duration: 0.68s)******************
> ***** Running training (total_iters=7065) *****
> Beginning of Epoch 1/1, Total Generation Batches 7065
> ------------------------------------------------------
> Free memory : 4.321960 (GigaBytes)  
> Total memory: 39.393860 (GigaBytes)  
> Requested memory: 0.684814 (GigaBytes) 
> Setting maximum total tokens (input + output) to 1088 
> WorkSpace: 0x7fe7f2000000 
> ------------------------------------------------------
> Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
> Traceback (most recent call last):
>   File "/home/lgh/models/trustworthy-alignment/training/main.py", line 765, in <module>
>     main()
>   File "/home/lgh/models/trustworthy-alignment/training/main.py", line 569, in main
>     out = trainer.generate_experience(batch_prompt['prompt'],
>   File "/home/lgh/models/trustworthy-alignment/dschat/rlhf/ppo_trainer.py", line 216, in generate_experience
>     seq, metric_dict = self._generate_sequence(prompts, mask, step, right_answers, wrong_answers)
>   File "/home/lgh/models/trustworthy-alignment/dschat/rlhf/ppo_trainer.py", line 151, in _generate_sequence
>     seq = self.actor_model.module.generate(
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 256, in generate
>     generate_ret_vals = self._generate(*inputs, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2048, in generate
>     result = self._sample(
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/transformers/generation/utils.py", line 3008, in _sample
>     outputs = self(**model_inputs, return_dict=True)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
>     outputs = self.model(
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 955, in forward
>     past_key_values = DynamicCache.from_legacy_cache(past_key_values)
>   File "/home/lgh/anaconda3/envs/rl/lib/python3.10/site-packages/transformers/cache_utils.py", line 468, in from_legacy_cache
>     key_states, value_states = past_key_values[layer_idx]
> ValueError: not enough values to unpack (expected 2, got 1)
> [2024-12-17 22:05:03,214] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3345648
> [2024-12-17 22:05:04,147] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3345649
> [2024-12-17 22:05:04,179] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3345650
> [2024-12-17 22:05:04,179] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3345651
> ‘’‘

**Comment by zmzhang2000** [comment]
Our code is tested with `transformers==4.35.0` and `Llama-2`. To run with other version of packages and models, please refer to their documents and configs and adapt our code.
